name: AQI Feature Pipeline

on:
  schedule:
    - cron: "0 */2 * * *"   # runs every 2 hours
  workflow_dispatch:         # allows manual trigger

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name:
